CREATE DATABASE IF NOT EXISTS meshpay_user;
CREATE DATABASE IF NOT EXISTS meshpay_relay_1;
CREATE DATABASE IF NOT EXISTS meshpay_relay_2;
CREATE DATABASE IF NOT EXISTS meshpay_gateway;
CREATE DATABASE IF NOT EXISTS meshpay_bank;
CREATE DATABASE IF NOT EXISTS meshpay_transaction;
